/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculatorr;



/**
 *
 * @author farhad
 */
public class Calculatorr extends javax.swing.JFrame {
    //private JTextField display;

    /**
     * Creates new form Calculatorr
     */
    double Num1,Num2;
    double ANS;
    String opr;
    
    
    public Calculatorr() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void Enter(String s)
    {
        String s1=jBDisplay.getText()+s;
        jBDisplay.setText(s1);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton40 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jBDisplay = new javax.swing.JTextField();
        jBMultiply = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jBPlus = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jPercent = new javax.swing.JButton();
        jBZero = new javax.swing.JButton();
        jBDot = new javax.swing.JButton();
        jBEq = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jBRoot = new javax.swing.JButton();
        jBDivide = new javax.swing.JButton();
        jBMinus = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton197 = new javax.swing.JButton();
        jButton198 = new javax.swing.JButton();
        jButton199 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton202 = new javax.swing.JButton();
        jButton203 = new javax.swing.JButton();
        jButton204 = new javax.swing.JButton();
        jButton205 = new javax.swing.JButton();
        jButton206 = new javax.swing.JButton();
        jButton207 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton208 = new javax.swing.JButton();
        jButton209 = new javax.swing.JButton();
        jButton210 = new javax.swing.JButton();
        jButton211 = new javax.swing.JButton();
        jButton212 = new javax.swing.JButton();
        jButton213 = new javax.swing.JButton();
        jButton214 = new javax.swing.JButton();
        jButton215 = new javax.swing.JButton();
        jButton216 = new javax.swing.JButton();
        jButton217 = new javax.swing.JButton();
        jButton218 = new javax.swing.JButton();
        jButton219 = new javax.swing.JButton();
        jButton220 = new javax.swing.JButton();
        jButton221 = new javax.swing.JButton();
        jButton222 = new javax.swing.JButton();
        jButton223 = new javax.swing.JButton();
        jButton224 = new javax.swing.JButton();
        jButton225 = new javax.swing.JButton();
        jButton226 = new javax.swing.JButton();
        jButton227 = new javax.swing.JButton();
        jButton228 = new javax.swing.JButton();
        jButton229 = new javax.swing.JButton();
        jButton230 = new javax.swing.JButton();
        jButton231 = new javax.swing.JButton();
        jButton232 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton233 = new javax.swing.JButton();
        jButton234 = new javax.swing.JButton();
        jButton235 = new javax.swing.JButton();
        jButton236 = new javax.swing.JButton();
        jButton237 = new javax.swing.JButton();
        jButton238 = new javax.swing.JButton();
        jButton239 = new javax.swing.JButton();
        jButton240 = new javax.swing.JButton();
        jButton241 = new javax.swing.JButton();
        jButton242 = new javax.swing.JButton();
        jButton243 = new javax.swing.JButton();
        jButton244 = new javax.swing.JButton();
        jButton245 = new javax.swing.JButton();
        jButton246 = new javax.swing.JButton();
        jButton247 = new javax.swing.JButton();
        jButton248 = new javax.swing.JButton();
        jButton249 = new javax.swing.JButton();
        jButton250 = new javax.swing.JButton();
        jButton251 = new javax.swing.JButton();
        jButton252 = new javax.swing.JButton();
        jButton253 = new javax.swing.JButton();
        jButton254 = new javax.swing.JButton();
        jButton255 = new javax.swing.JButton();
        jButton256 = new javax.swing.JButton();
        jButton257 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton258 = new javax.swing.JButton();
        jBDEL = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jButton263 = new javax.swing.JButton();
        jButton264 = new javax.swing.JButton();
        jButton265 = new javax.swing.JButton();
        jButton266 = new javax.swing.JButton();
        jBAC = new javax.swing.JButton();
        jButton267 = new javax.swing.JButton();
        jButton268 = new javax.swing.JButton();
        jButton269 = new javax.swing.JButton();
        jButton270 = new javax.swing.JButton();
        jButton271 = new javax.swing.JButton();
        jButton272 = new javax.swing.JButton();
        jButton273 = new javax.swing.JButton();
        jButton274 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton275 = new javax.swing.JButton();
        jButton276 = new javax.swing.JButton();
        jButton277 = new javax.swing.JButton();
        jButton278 = new javax.swing.JButton();
        jButton279 = new javax.swing.JButton();
        jButton280 = new javax.swing.JButton();
        jButton281 = new javax.swing.JButton();
        jButton282 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton283 = new javax.swing.JButton();
        jButton284 = new javax.swing.JButton();
        jButton285 = new javax.swing.JButton();
        jButton286 = new javax.swing.JButton();
        jButton287 = new javax.swing.JButton();
        jButton288 = new javax.swing.JButton();
        jButton289 = new javax.swing.JButton();
        jButton290 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();

        jButton40.setText("jButton1");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jButton93.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jButton93.setText("AC");

        jButton95.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton95.setText("7");

        jButton94.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jButton94.setText("DEL");

        jButton84.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton84.setText("7");

        jButton98.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jButton98.setText("AC");

        jButton83.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jButton83.setText("DEL");

        jButton96.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton96.setText("8");

        jButton91.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton91.setText("8");

        jButton92.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton92.setText("9");

        jButton97.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton97.setText("9");

        jButton13.setText("jButton13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jBDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 100));

        jBMultiply.setFont(new java.awt.Font("Cooper Black", 2, 36)); // NOI18N
        jBMultiply.setText("*");
        jBMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(jBMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jB4.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jB5.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        getContentPane().add(jB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jB6.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        getContentPane().add(jB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jButton163.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton163, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jButton164.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton164, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jButton165.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton165, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jButton166.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton166, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jBPlus.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jBPlus.setText("+");
        jBPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jBPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jB1.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jB2.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jB3.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jButton171.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton171, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jButton172.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton172, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jButton173.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton173, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jButton174.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton174, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jPercent.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jPercent.setText("%");
        jPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPercentActionPerformed(evt);
            }
        });
        getContentPane().add(jPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jBZero.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jBZero.setText("0");
        jBZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBZeroActionPerformed(evt);
            }
        });
        getContentPane().add(jBZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jBDot.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jBDot.setText(".");
        jBDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDotActionPerformed(evt);
            }
        });
        getContentPane().add(jBDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jBEq.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jBEq.setText("=");
        jBEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEqActionPerformed(evt);
            }
        });
        getContentPane().add(jBEq, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 74, 70));

        jButton179.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton179, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jButton180.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton180, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jButton181.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton181, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jBRoot.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jBRoot.setText("√");
        jBRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRootActionPerformed(evt);
            }
        });
        getContentPane().add(jBRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jBDivide.setFont(new java.awt.Font("Cooper Black", 2, 24)); // NOI18N
        jBDivide.setText("/");
        jBDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jBDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 74, 70));

        jBMinus.setFont(new java.awt.Font("Cooper Black", 3, 48)); // NOI18N
        jBMinus.setText("-");
        jBMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 74, 70));

        jButton183.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jButton183.setText("=");
        getContentPane().add(jButton183, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jButton184.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton184.setText("×");
        getContentPane().add(jButton184, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jButton185.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton185.setText("4");
        getContentPane().add(jButton185, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jButton186.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton186.setText("5");
        getContentPane().add(jButton186, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jButton187.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton187.setText("6");
        getContentPane().add(jButton187, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jButton188.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton188, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jButton189.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton189, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jButton190.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton190, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jButton191.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton191, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jButton192.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jButton192.setText("+");
        getContentPane().add(jButton192, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jButton193.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton193.setText("1");
        getContentPane().add(jButton193, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jButton194.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton194.setText("2");
        getContentPane().add(jButton194, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jButton195.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton195.setText("3");
        getContentPane().add(jButton195, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jButton196.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton196, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jButton197.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton197, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jButton198.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton198, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jButton199.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton199, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jButton200.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton200.setText("%");
        getContentPane().add(jButton200, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jButton201.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton201.setText("0");
        getContentPane().add(jButton201, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jButton202.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton202.setText(".");
        getContentPane().add(jButton202, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jButton203.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jButton203.setText("=");
        getContentPane().add(jButton203, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 74, 70));

        jButton204.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton204, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jButton205.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton205, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jButton206.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton206, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jButton207.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton207.setText("√");
        getContentPane().add(jButton207, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jButton21.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton21.setText("÷");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 74, 70));

        jButton22.setFont(new java.awt.Font("Cooper Black", 3, 48)); // NOI18N
        jButton22.setText("-");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 74, 70));

        jButton208.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jButton208.setText("=");
        getContentPane().add(jButton208, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jButton209.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton209.setText("×");
        getContentPane().add(jButton209, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jButton210.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton210.setText("4");
        getContentPane().add(jButton210, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jButton211.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton211.setText("5");
        getContentPane().add(jButton211, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jButton212.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton212.setText("6");
        getContentPane().add(jButton212, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jButton213.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton213, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jButton214.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton214, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jButton215.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton215, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jButton216.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton216, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jButton217.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jButton217.setText("+");
        getContentPane().add(jButton217, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jButton218.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton218.setText("1");
        getContentPane().add(jButton218, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jButton219.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton219.setText("2");
        getContentPane().add(jButton219, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jButton220.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton220.setText("3");
        getContentPane().add(jButton220, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jButton221.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton221, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jButton222.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton222, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jButton223.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton223, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jButton224.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton224, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jButton225.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton225.setText("%");
        getContentPane().add(jButton225, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jButton226.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton226.setText("0");
        getContentPane().add(jButton226, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jButton227.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton227.setText(".");
        getContentPane().add(jButton227, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jButton228.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jButton228.setText("=");
        getContentPane().add(jButton228, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 74, 70));

        jButton229.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton229, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jButton230.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton230, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jButton231.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton231, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jButton232.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton232.setText("√");
        getContentPane().add(jButton232, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jButton23.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton23.setText("÷");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 74, 70));

        jButton24.setFont(new java.awt.Font("Cooper Black", 3, 48)); // NOI18N
        jButton24.setText("-");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 74, 70));

        jButton233.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jButton233.setText("=");
        getContentPane().add(jButton233, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jButton234.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton234.setText("×");
        getContentPane().add(jButton234, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jButton235.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton235.setText("4");
        getContentPane().add(jButton235, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jButton236.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton236.setText("5");
        getContentPane().add(jButton236, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jButton237.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton237.setText("6");
        getContentPane().add(jButton237, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jButton238.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton238, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 74, 70));

        jButton239.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton239, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, 70));

        jButton240.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton240, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 74, 70));

        jButton241.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton241, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 74, 70));

        jButton242.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jButton242.setText("+");
        getContentPane().add(jButton242, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jButton243.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton243.setText("1");
        getContentPane().add(jButton243, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jButton244.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton244.setText("2");
        getContentPane().add(jButton244, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jButton245.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton245.setText("3");
        getContentPane().add(jButton245, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jButton246.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton246, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 74, 70));

        jButton247.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton247, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 70));

        jButton248.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton248, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 74, 70));

        jButton249.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton249, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 74, 70));

        jButton250.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton250.setText("%");
        getContentPane().add(jButton250, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jButton251.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton251.setText("0");
        getContentPane().add(jButton251, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jButton252.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton252.setText(".");
        getContentPane().add(jButton252, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jButton253.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jButton253.setText("=");
        getContentPane().add(jButton253, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 74, 70));

        jButton254.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton254, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 74, 70));

        jButton255.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton255, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 74, 70));

        jButton256.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton256, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 74, 70));

        jButton257.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton257.setText("√");
        getContentPane().add(jButton257, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jButton25.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton25.setText("÷");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 74, 70));

        jButton26.setFont(new java.awt.Font("Cooper Black", 3, 48)); // NOI18N
        jButton26.setText("-");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 74, 70));

        jButton258.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jButton258.setText("=");
        getContentPane().add(jButton258, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 74, 70));

        jBDEL.setFont(new java.awt.Font("Cooper Black", 2, 18)); // NOI18N
        jBDEL.setText("DEL");
        jBDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDELActionPerformed(evt);
            }
        });
        getContentPane().add(jBDEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jB7.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        getContentPane().add(jB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jB8.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });
        getContentPane().add(jB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jB9.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });
        getContentPane().add(jB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jButton263.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton263, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jButton264.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton264, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jButton265.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton265, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jButton266.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton266, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jBAC.setFont(new java.awt.Font("Cooper Black", 2, 24)); // NOI18N
        jBAC.setText("AC");
        jBAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBACActionPerformed(evt);
            }
        });
        getContentPane().add(jBAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 74, 70));

        jButton267.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton267.setText("×");
        getContentPane().add(jButton267, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jButton268.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton268.setText("4");
        getContentPane().add(jButton268, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jButton269.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton269.setText("5");
        getContentPane().add(jButton269, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jButton270.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton270.setText("6");
        getContentPane().add(jButton270, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jButton271.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton271, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jButton272.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton272, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jButton273.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton273, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jButton274.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton274, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jButton27.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton27.setText("÷");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 74, 70));

        jButton275.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton275.setText("×");
        getContentPane().add(jButton275, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jButton276.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton276.setText("4");
        getContentPane().add(jButton276, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jButton277.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton277.setText("5");
        getContentPane().add(jButton277, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jButton278.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton278.setText("6");
        getContentPane().add(jButton278, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jButton279.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton279, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jButton280.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton280, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jButton281.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton281, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jButton282.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton282, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jButton28.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton28.setText("÷");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 74, 70));

        jButton283.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton283.setText("×");
        getContentPane().add(jButton283, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jButton284.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton284.setText("4");
        getContentPane().add(jButton284, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jButton285.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton285.setText("5");
        getContentPane().add(jButton285, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jButton286.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        jButton286.setText("6");
        getContentPane().add(jButton286, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jButton287.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jButton287, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 74, 70));

        jButton288.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton288, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 70));

        jButton289.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton289, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 74, 70));

        jButton290.setFont(new java.awt.Font("Ink Free", 2, 48)); // NOI18N
        getContentPane().add(jButton290, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 74, 70));

        jButton29.setFont(new java.awt.Font("Cooper Black", 2, 48)); // NOI18N
        jButton29.setText("÷");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 74, 70));

        pack();
    }// </editor-fold>                        

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        Enter("7");
    }                                   

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {                                    
       Enter("8");        // TODO add your handling code here:
    }                                   

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 Enter("9");        // TODO add your handling code here:
    }                                   

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 Enter("4");        // TODO add your handling code here:
    }                                   

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 Enter("5");        // TODO add your handling code here:
    }                                   

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 Enter("6");        // TODO add your handling code here:
    }                                   

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 Enter("1");        // TODO add your handling code here:
    }                                   

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 Enter("2");        // TODO add your handling code here:
    }                                   

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
 Enter("3");        // TODO add your handling code here:
    }                                   

    private void jBZeroActionPerformed(java.awt.event.ActionEvent evt) {                                       
 Enter("0");        // TODO add your handling code here:
    }                                      

    private void jBDivideActionPerformed(java.awt.event.ActionEvent evt) {                                         
          Num1=Double.parseDouble(jBDisplay.getText());
          jBDisplay.setText("");
          opr="/";
    }                                        

    private void jBMultiplyActionPerformed(java.awt.event.ActionEvent evt) {                                           
         Num1=Double.parseDouble(jBDisplay.getText());
          jBDisplay.setText("");
          opr="*";
    }                                          

    private void jBPlusActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         Num1=Double.parseDouble(jBDisplay.getText());
          jBDisplay.setText("");
          opr="+";
    }                                      

    private void jBMinusActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
         Num1=Double.parseDouble(jBDisplay.getText());
          jBDisplay.setText("");
          opr="-";
    }                                       

    private void jBACActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
         jBDisplay.setText("");
    }                                    

    private void jBDELActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        String text = jBDisplay.getText();  
              if (text.length() > 0) {              
        jBDisplay.setText(text.substring(0, text.length() - 1)); 
    }
        
    }                                     

    private void jBDotActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        String text = jBDisplay.getText(); // Get current text from display
    if (!text.contains(".")) { // Check if there's no dot already
        jBDisplay.setText(text + "."); // Append the dot to the current input
    }
    }                                     

    private void jBEqActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Num2=Double.parseDouble(jBDisplay.getText());
        switch(opr) {
        case "+":  
            ANS = Num1 + Num2;
            break;
        case "-":  
            ANS = Num1 - Num2;
            break;
        case "*":  
            ANS = Num1 * Num2;
            break;
        case "/":  
            if (Num2 != 0) {
                ANS = Num1 / Num2;
            } else {
                jBDisplay.setText("Error");  
                return;
            }
            break;
        default:
            ANS = Num1;  
            break;
    }
    
    jBDisplay.setText(String.valueOf(ANS));  
    }                                    

    private void jBRootActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         try {
        double num = Double.parseDouble(jBDisplay.getText());  
        if (num >= 0) {  
            double result = Math.sqrt(num);  
            jBDisplay.setText(String.valueOf(result));  
        } else {
            jBDisplay.setText("Error");  
        }
    } catch (NumberFormatException e) {
        jBDisplay.setText("Error");  
    }
    }                                      

    private void jPercentActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try {
        double num = Double.parseDouble(jBDisplay.getText());  
        double result = num / 100;  
        jBDisplay.setText(String.valueOf(result));  
    } catch (NumberFormatException e) {
        jBDisplay.setText("Error");  
    }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatorr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBAC;
    private javax.swing.JButton jBDEL;
    private javax.swing.JTextField jBDisplay;
    private javax.swing.JButton jBDivide;
    private javax.swing.JButton jBDot;
    private javax.swing.JButton jBEq;
    private javax.swing.JButton jBMinus;
    private javax.swing.JButton jBMultiply;
    private javax.swing.JButton jBPlus;
    private javax.swing.JButton jBRoot;
    private javax.swing.JButton jBZero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JButton jButton199;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton202;
    private javax.swing.JButton jButton203;
    private javax.swing.JButton jButton204;
    private javax.swing.JButton jButton205;
    private javax.swing.JButton jButton206;
    private javax.swing.JButton jButton207;
    private javax.swing.JButton jButton208;
    private javax.swing.JButton jButton209;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton210;
    private javax.swing.JButton jButton211;
    private javax.swing.JButton jButton212;
    private javax.swing.JButton jButton213;
    private javax.swing.JButton jButton214;
    private javax.swing.JButton jButton215;
    private javax.swing.JButton jButton216;
    private javax.swing.JButton jButton217;
    private javax.swing.JButton jButton218;
    private javax.swing.JButton jButton219;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton220;
    private javax.swing.JButton jButton221;
    private javax.swing.JButton jButton222;
    private javax.swing.JButton jButton223;
    private javax.swing.JButton jButton224;
    private javax.swing.JButton jButton225;
    private javax.swing.JButton jButton226;
    private javax.swing.JButton jButton227;
    private javax.swing.JButton jButton228;
    private javax.swing.JButton jButton229;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton230;
    private javax.swing.JButton jButton231;
    private javax.swing.JButton jButton232;
    private javax.swing.JButton jButton233;
    private javax.swing.JButton jButton234;
    private javax.swing.JButton jButton235;
    private javax.swing.JButton jButton236;
    private javax.swing.JButton jButton237;
    private javax.swing.JButton jButton238;
    private javax.swing.JButton jButton239;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton240;
    private javax.swing.JButton jButton241;
    private javax.swing.JButton jButton242;
    private javax.swing.JButton jButton243;
    private javax.swing.JButton jButton244;
    private javax.swing.JButton jButton245;
    private javax.swing.JButton jButton246;
    private javax.swing.JButton jButton247;
    private javax.swing.JButton jButton248;
    private javax.swing.JButton jButton249;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton250;
    private javax.swing.JButton jButton251;
    private javax.swing.JButton jButton252;
    private javax.swing.JButton jButton253;
    private javax.swing.JButton jButton254;
    private javax.swing.JButton jButton255;
    private javax.swing.JButton jButton256;
    private javax.swing.JButton jButton257;
    private javax.swing.JButton jButton258;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton263;
    private javax.swing.JButton jButton264;
    private javax.swing.JButton jButton265;
    private javax.swing.JButton jButton266;
    private javax.swing.JButton jButton267;
    private javax.swing.JButton jButton268;
    private javax.swing.JButton jButton269;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton270;
    private javax.swing.JButton jButton271;
    private javax.swing.JButton jButton272;
    private javax.swing.JButton jButton273;
    private javax.swing.JButton jButton274;
    private javax.swing.JButton jButton275;
    private javax.swing.JButton jButton276;
    private javax.swing.JButton jButton277;
    private javax.swing.JButton jButton278;
    private javax.swing.JButton jButton279;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton280;
    private javax.swing.JButton jButton281;
    private javax.swing.JButton jButton282;
    private javax.swing.JButton jButton283;
    private javax.swing.JButton jButton284;
    private javax.swing.JButton jButton285;
    private javax.swing.JButton jButton286;
    private javax.swing.JButton jButton287;
    private javax.swing.JButton jButton288;
    private javax.swing.JButton jButton289;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton290;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jPercent;
    // End of variables declaration                   
}
